stages:
  - build
  - docker

# --------------------BUILD-------------------------
.build-app-template:
  stage: build
  image: maven:3.9.9-amazoncorretto-21
  cache:
    paths:
      - .m2/repository
  script:
    - mvn clean package -pl $SERVICE_NAME -am -DskipTests
  artifacts:
    paths:
      - $SERVICE_NAME/target/*.jar
    expire_in: 1 hour

build-api-gateway:
  extends: .build-app-template
  variables:
    SERVICE_NAME: "api-gateway"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - api-gateway/**/*
        - common-dto/**/*
        - pom.xml

build-common-dto:
  extends: .build-app-template
  variables:
    SERVICE_NAME: "common-dto"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - common-dto/**/*
        - pom.xml

build-common-utils:
  extends: .build-app-template
  variables:
    SERVICE_NAME: "common-utils"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - common-utils/**/*
        - pom.xml

build-booking-service:
  extends: .build-app-template
  variables:
    SERVICE_NAME: "booking-service"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - booking-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml

build-notification-service:
  extends: .build-app-template
  variables:
    SERVICE_NAME: "notification-service"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - notification-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml

build-payment-service:
  extends: .build-app-template
  variables:
    SERVICE_NAME: "payment-service"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - payment-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml

build-service-registry:
  extends: .build-app-template
  variables:
    SERVICE_NAME: "service-registry"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - service-registry/**/*
        - pom.xml

build-config-server:
  extends: .build-app-template
  variables:
    SERVICE_NAME: "config-server"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - config-server/**/*
        - pom.xml

build-user-service:
  extends: .build-app-template
  variables:
    SERVICE_NAME: "user-service"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - user-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml

build-hotel-service:
  extends: .build-app-template
  variables:
    SERVICE_NAME: "hotel-service"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - hotel-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml

build-event-hotels-service:
  extends: .build-app-template
  variables:
    SERVICE_NAME: "event-hotels-service"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - event-hotels-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml

build-event-booking-service:
  extends: .build-app-template
  variables:
    SERVICE_NAME: "event-booking-service"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - event-booking-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml
# --------------------DOCKER-------------------------
.docker-job-template:
  stage: docker
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "$docker_password" | docker login -u "$docker_user" --password-stdin
    - TAG="v$CI_PIPELINE_IID"
    - docker build --build-arg SERVICE_NAME=$SERVICE_NAME -t $docker_user/$SERVICE_NAME:$TAG -t $docker_user/$SERVICE_NAME:latest .
    - docker push $docker_user/$SERVICE_NAME:$TAG
    - docker push $docker_user/$SERVICE_NAME:latest

docker-api-gateway:
  extends: .docker-job-template
  variables:
    SERVICE_NAME: "api-gateway"
  needs:
    - job: build-api-gateway
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - api-gateway/**/*
        - common-dto/**/*
        - pom.xml

docker-booking-service:
  extends: .docker-job-template
  variables:
    SERVICE_NAME: "booking-service"
  needs:
    - job: build-booking-service
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - booking-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml

docker-notification-service:
  extends: .docker-job-template
  variables:
    SERVICE_NAME: "notification-service"
  needs:
    - job: build-notification-service
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - notification-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml

docker-payment-service:
  extends: .docker-job-template
  variables:
    SERVICE_NAME: "payment-service"
  needs:
    - job: build-payment-service
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - payment-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml

docker-service-registry:
  extends: .docker-job-template
  variables:
    SERVICE_NAME: "service-registry"
  needs:
    - job: build-service-registry
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - service-registry/**/*
        - pom.xml

docker-config-server:
  extends: .docker-job-template
  variables:
    SERVICE_NAME: "config-server"
  needs:
    - job: build-config-server
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - config-server/**/*
        - pom.xml

docker-user-service:
  extends: .docker-job-template
  variables:
    SERVICE_NAME: "user-service"
  needs:
    - job: build-user-service
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - user-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml

docker-hotel-service:
  extends: .docker-job-template
  variables:
    SERVICE_NAME: "hotel-service"
  needs:
    - job: build-hotel-service
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - hotel-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml

docker-event-hotels-service:
  extends: .docker-job-template
  variables:
    SERVICE_NAME: "event-hotels-service"
  needs:
    - job: build-event-hotels-service
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - event-hotels-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml

docker-event-booking-service:
  extends: .docker-job-template
  variables:
    SERVICE_NAME: "event-booking-service"
  needs:
    - job: build-event-booking-service
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - event-booking-service/**/*
        - common-dto/**/*
        - common-utils/**/*
        - pom.xml